### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fortran#91]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/fortran/issues/82)
- [x] [Add key features](https://github.com/exercism/fortran/issues/83)
- [x] [Add tags](https://github.com/exercism/fortran/issues/84)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/fortran/issues/85)
- [ ] [Update status of track](https://github.com/exercism/fortran/issues/89)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/fortran/issues/90)
- [ ] [Pass linting checks](https://github.com/exercism/fortran/issues/86)
- [ ] [Build Test Runner](https://github.com/exercism/fortran/issues/87)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/fortran/issues/88) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by pclausen** [comment]
@ErikSchierboom I think we have made progress on most of these but perhaps we could review together at some point?

**Comment by ErikSchierboom** [comment]
@pclausen Yeah sure. Maybe sometime next week?

**Comment by ErikSchierboom** [comment]
The track has been launched so we can close this.
